services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=dani
      - POSTGRES_PASSWORD=daniadmin123
    ports:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dani@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
